// Writes the raw mock data for Acme Builders to data/mock/acme-builders/, as the harness would receive it:
// one folder per project, a photo drop per week (JSON lines, one line per photo), an activity log and an
// outcomes log. The model is hub/site/sim-data.js, so the hub simulator and these files always agree.
// Also writes data/mock/media-pool/media-pool.js (the photo index the hub pages load) from credits.json.
//
//   node scripts/mock/export.mjs
//
// Every value is AUTHORED example data except the 20 building records (NYC Open Data) and the photos
// (openly licensed, see data/mock/media-pool/CREDITS.md).
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = join(REPO, 'data', 'mock', 'acme-builders');
const POOL = join(REPO, 'data', 'mock', 'media-pool');

// photo index first, so the model can attach a real file to every sampled photo
const MEDIA = {};
if (existsSync(join(POOL, 'credits.json'))) {
  for (const c of JSON.parse(readFileSync(join(POOL, 'credits.json'), 'utf8'))) (MEDIA[c.category] ||= []).push(c.file.replace(/^.*media-pool\//, ''));
  writeFileSync(join(POOL, 'media-pool.js'),
    '/* Generated by scripts/mock/export.mjs from credits.json. Category → photo files. */\n' +
    '(function(){ var G=(typeof globalThis!=="undefined"?globalThis:window); G.MEDIA=' + JSON.stringify(MEDIA) + '; })();\n');
}
globalThis.MEDIA = MEDIA;
await import(join(REPO, 'hub', 'site', 'sim-data.js'));
const S = globalThis.SIM;

const iso = t => new Date(t).toISOString().slice(0, 10);
const slug = s => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const isoWeek = t => { const d = new Date(t); const y = d.getUTCFullYear(); const jan1 = Date.UTC(y, 0, 1); return y + '-W' + String(Math.ceil(((t - jan1) / 864e5 + new Date(jan1).getUTCDay() + 1) / 7)).padStart(2, '0'); };
const jsonl = rows => rows.map(r => JSON.stringify(r)).join('\n') + (rows.length ? '\n' : '');
let seed = 7; const R = () => { seed = (seed * 9301 + 49297) % 233280; return seed / 233280; };
const pick = a => a[Math.floor(R() * a.length)];

rmSync(OUT, { recursive: true, force: true });
mkdirSync(join(OUT, 'projects'), { recursive: true });

writeFileSync(join(OUT, 'firm.json'), JSON.stringify({
  firm: 'Acme Builders', note: 'Example general contractor. At most ' + S.MAXLIVE + ' live projects at once.',
  demo_today: iso(S.TODAY), roles: S.ROLES,
  sources: {
    buildings: 'NYC Open Data, DOB Job Application Filings (ic3t-wcy2). Street, neighborhood, building class, stories, floor area and job number only. House numbers and personal names dropped. Dates are authored.',
    photos: 'Openly licensed photos, see ../media-pool/CREDITS.md. Each photo in a weekly drop points at one pool file.'
  }
}, null, 2));

const QUERIES = {
  'Site work': ['excavation depth north side', 'site fence photos', 'utility markout'],
  'Structure': ['slab pour level 3', 'rebar before pour', 'formwork stripped'],
  'Framing': ['studs level 2 east wing', 'framing inspection photos'],
  'Rough-in': ['plumbing before drywall', 'electrical rough-in unit', 'duct run above ceiling'],
  'Close-in': ['plumbing before drywall', 'water near windows', 'insulation before board'],
  'Finishes': ['water near windows', 'tile finish unit', 'punch list photos'],
  'Closeout': ['closeout photos per unit', 'final exterior photos']
};
const UPLOADER = { site: 'super', concrete: 'super', steel: 'super', framing: 'super', plumbing: 'trade', electrical: 'super', hvac: 'super', insulation: 'super', drywall: 'super', finishes: 'pe', paint: 'pe', exterior: 'pe' };

const index = [];
for (const p of S.projects) {
  const dir = join(OUT, 'projects', p.id + '-' + slug(p.name));
  mkdirSync(join(dir, 'media'), { recursive: true });
  writeFileSync(join(dir, 'project.json'), JSON.stringify({
    id: p.id, name: p.name, type: p.typeLabel, street: p.street, neighborhood: p.neighborhood, borough: p.borough,
    levels: p.levels, units: p.units, start: iso(S.weekDate(p.startWeek)), end: iso(S.weekDate(p.endWeek)),
    status_on_demo_day: S.status(p, S.TODAY_WEEK), source_record: p.source,
    phases: p.phases.map(ph => ({ name: ph.name, start: iso(S.weekDate(ph.from)), end: iso(S.weekDate(ph.to) + 4 * 864e5) }))
  }, null, 2));

  // weekly photo drops: only weeks up to demo day exist, like a real firm's folder
  const byWeek = {};
  for (const x of p.photos) if (x.w <= S.TODAY_WEEK) (byWeek[x.w] ||= []).push(x);
  let nPhotos = 0;
  for (const [w, list] of Object.entries(byWeek)) {
    const t = S.weekDate(+w);
    writeFileSync(join(dir, 'media', isoWeek(t) + '.jsonl'), jsonl(list.map(x => ({
      photo: x.id, taken_at: iso(t + x.day * 864e5) + 'T' + String(7 + Math.floor(R() * 9)).padStart(2, '0') + ':' + String(Math.floor(R() * 60)).padStart(2, '0'),
      uploaded_by: UPLOADER[x.trade] || 'super', level: x.level, unit: x.unit, caption: x.trade + (x.unit ? ' · unit ' + x.unit : ''),
      file: x.file ? '../../../media-pool/' + x.file : null,
      ...(x.water ? { note: 'stain near window?' } : {}), ...(x.hazard ? { note: x.hazard } : {})
    }))));
    nPhotos += list.length;
  }

  // activity: what people did in the app that week (the harness learns from this)
  const act = [], out = [];
  for (const wk of p.weeks) {
    if (wk.w > S.TODAY_WEEK) break;
    const t = S.weekDate(wk.w), q = QUERIES[wk.phase] || ['photos this week'];
    for (let i = 0; i < wk.searches; i++) act.push({ at: iso(t + Math.floor(R() * 5) * 864e5), role: pick(['super', 'pm', 'pe']), action: 'search', query: pick(q), result: i < wk.failed ? 'no' : 'yes' });
    if (wk.packMin) act.push({ at: iso(t + 4 * 864e5), role: 'pm', action: 'owner_pack_by_hand', minutes: wk.packMin });
    for (let i = 0; i < wk.missing; i++) out.push({ at: iso(t), kind: 'closed_without_open_wall_photo', level: 1 + Math.floor(R() * p.levels), unit: null });
    for (let i = 0; i < wk.reopened; i++) out.push({ at: iso(t + (20 + Math.floor(R() * 30)) * 7 * 864e5), kind: 'wall_reopened', hours_lost: 6 + Math.floor(R() * 10) });
    if (wk.water) out.push({ at: iso(t), kind: 'water_stain', found: wk.waterEarly ? 'same day' : 'at closeout' });
  }
  writeFileSync(join(dir, 'activity.jsonl'), jsonl(act));
  writeFileSync(join(dir, 'outcomes.jsonl'), jsonl(out.filter(o => o.at <= iso(S.TODAY)).sort((a, b) => a.at < b.at ? -1 : 1)));
  index.push({ id: p.id, folder: 'projects/' + p.id + '-' + slug(p.name), name: p.name, status: S.status(p, S.TODAY_WEEK), photo_drops: Object.keys(byWeek).length, photos_sampled: nPhotos, activity: act.length, outcomes: out.length });
}
writeFileSync(join(OUT, 'index.json'), JSON.stringify(index, null, 2));

// what the harness is expected to learn when it replays this data (output, not input)
mkdirSync(join(OUT, 'expected'), { recursive: true });
writeFileSync(join(OUT, 'expected', 'harness-versions.json'), JSON.stringify(S.versions.map(v => ({
  v: v.v, date: iso(v.date), capability: v.cap, why: v.why, changes: v.changes, rolled_back: v.rolledBackWeek != null ? iso(S.weekDate(v.rolledBackWeek)) : null
})), null, 2));

console.log('wrote', index.length, 'projects,', index.reduce((a, x) => a + x.photo_drops, 0), 'weekly photo drops,', index.reduce((a, x) => a + x.photos_sampled, 0), 'photos,', Object.keys(MEDIA).length, 'photo categories');
