#!/usr/bin/env node
/* 3PT · README architecture infographic → docs/assets/architecture.svg
   The monorepo as three lanes: ui/ (surfaces), harness/ (the pipeline), infra/ (batteries). Dependency direction
   apps → packages → @3pt/core; surfaces reach the harness only over HTTP; batteries are injected at the edge
   (cli, api, worker) and stages never import them; Atlas under everything. Workspace names are read from the
   tree by hand at generation time and listed in docs/10-architecture.md. Same tokens as the banner (D2 dark).
   Run: node scripts/architecture.mjs */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const W = 1600, H = 620;
const T = { canvas:'#0F1216', surface:'#151A21', raised:'#1A2029', ink:'#E6E9EE', muted:'#A3ADBB', faint:'#7B8694',
  line:'#2A323D', lineStrong:'#5E6C85', accent:'#FF6B4A', plan:'#8B7CF6', build:'#E0A33A', instrument:'#3FB886', core:'#3AA6D9', mongo:'#00ED64', alert:'#F06A61' };

const LANES = [
  { key:'ui', x: 64, w: 400, hue: T.plan, title:'ui/ · SURFACES', sub:'inspectors and the app, over HTTP only',
    rows: [ ['apps', ['web · role-based app', 'pwa · installable inspector', 'macos · SwiftUI inspector', 'live · screens the harness composes']],
            ['packages', ['design-system · tokens', 'inspector-client · typed fetch']] ] },
  { key:'harness', x: 512, w: 560, hue: T.build, title:'harness/ · THE PIPELINE', sub:'the product: stages, the improver, the compiler onto Strands',
    rows: [ ['apps', ['cli · plan build instrument loop', 'api · HTTP over Atlas', 'worker · index transcribe tier migrate']],
            ['packages', ['core · Policy, Checkpoint, COLL.', 'plan', 'build · adapters', 'instrument · checks', 'improver · rewrites policy', 'media · indexers', 'strands · Policy → Strands harness']] ] },
  { key:'infra', x: 1120, w: 416, hue: T.instrument, title:'infra/ · BATTERIES', sub:'what the pipeline runs on, injected at the edge',
    rows: [ ['batteries', ['atlas · Sandbox, collections, indexes', 'blob · gridfs | r2 | fs', 'artifacts · checkpoint bundles', 'repo · git, worktrees, tags', 'tracing · LangSmith, M-* reader', 'box · Colima VM + Ansible']] ] },
];

const box = (x, y, w, text, hue, strong=false) => `<rect x="${x}" y="${y}" width="${w}" height="26" rx="6" fill="${strong?T.raised:T.surface}" stroke="${hue}" stroke-opacity="${strong?.9:.5}" stroke-width="${strong?1.4:1}"/><text class="mono tiny" x="${x+10}" y="${y+17}" fill="${strong?T.ink:T.muted}">${text}</text>`;
const marker = hue => `<marker id="m-${hue.slice(1)}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10 Z" fill="${hue}"/></marker>`;

let lanes = '';
for (const L of LANES){
  const top = 104;
  let y = top + 78, body = '';
  for (const [group, items] of L.rows){
    body += `<text class="mono eyebrow" x="${L.x+18}" y="${y}" fill="${L.hue}">${group.toUpperCase()}</text>`; y += 12;
    const cols = L.w > 500 ? 2 : 1, cw = (L.w-36-(cols-1)*10)/cols;
    items.forEach((it, i) => { const cx = L.x+18+(i%cols)*(cw+10), cy = y + Math.floor(i/cols)*32; body += box(cx, cy, cw, it, L.hue, /core ·|cli ·|atlas ·|web ·/.test(it)); });
    y += Math.ceil(items.length/cols)*32 + 22;
  }
  L.bottom = y;
  lanes += `
    <g>
      <rect x="${L.x}" y="${top}" width="${L.w}" height="${Math.max(y-top-6, 300)}" rx="12" fill="${T.raised}" fill-opacity=".6" stroke="${L.hue}" stroke-opacity=".7" stroke-width="1.4"/>
      <text class="mono title" x="${L.x+18}" y="${top+30}" fill="${L.hue}">${L.title}</text>
      <text class="sans body" x="${L.x+18}" y="${top+48}" fill="${T.muted}">${L.sub}</text>
      ${body}
    </g>`;
}

const AY = 470;
const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" role="img" aria-labelledby="t d">
  <!-- Generated by scripts/architecture.mjs. Edit that file, not this one. Direction D2 dark. -->
  <title id="t">3PT monorepo: ui, harness and infra lanes; apps depend on packages depend on core; surfaces reach the harness over HTTP; batteries injected at the edge; MongoDB Atlas under everything.</title>
  <desc id="d">Three lanes side by side. ui holds the web, PWA, macOS and live apps and the design-system and inspector-client packages. harness holds the cli, api and worker apps and the core, plan, build, instrument, improver, media and strands packages. infra holds the atlas, blob, artifacts, repo, tracing and box batteries. Arrows: surfaces to api over HTTP; batteries into cli, api and worker; stages never import batteries; Atlas under all three lanes.</desc>
  <defs>
    <style>
      .sans{font-family:system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
      .mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;letter-spacing:.12em}
      .eyebrow{font-size:11px;font-weight:600}
      .title{font-size:14px;font-weight:700}
      .h{fill:${T.ink};font-size:30px;font-weight:800;letter-spacing:-.01em}
      .h .a{fill:${T.accent}}
      .body{font-size:13px;font-weight:400}
      .tiny{font-size:11px;font-weight:500;letter-spacing:.06em}
      .chip{font-size:11px;font-weight:600}
      .foot{fill:${T.faint};font-size:12px;font-weight:500}
    </style>
    ${[T.plan,T.build,T.instrument,T.mongo,T.alert,T.lineStrong].map(marker).join('')}
    <clipPath id="frame"><rect width="${W}" height="${H}" rx="12"/></clipPath>
  </defs>
  <g clip-path="url(#frame)">
    <rect width="${W}" height="${H}" fill="${T.canvas}"/>
    <text class="mono eyebrow" x="64" y="44" fill="${T.faint}">3PT · THE MONOREPO · THREE LANES · TURBOREPO + PNPM · 20 WORKSPACES</text>
    <text class="sans h" x="62" y="80">Surfaces talk HTTP. Stages never touch batteries. <tspan class="a">Atlas holds the state.</tspan></text>
    ${lanes}

    <!-- direction of dependency and the rules -->
    <line x1="464" y1="230" x2="506" y2="230" stroke="${T.plan}" stroke-width="1.8" stroke-dasharray="5 5" marker-end="url(#m-${T.plan.slice(1)})"/>
    <text class="mono tiny" x="485" y="218" text-anchor="middle" fill="${T.plan}">HTTP</text>
    <line x1="1120" y1="200" x2="1078" y2="200" stroke="${T.instrument}" stroke-width="1.8" marker-end="url(#m-${T.instrument.slice(1)})"/>
    <text class="mono tiny" x="1099" y="188" text-anchor="middle" fill="${T.instrument}">INJECT</text>
    <line x1="1120" y1="330" x2="1078" y2="330" stroke="${T.alert}" stroke-width="1.8" stroke-dasharray="2 4"/>
    <line x1="1092" y1="320" x2="1106" y2="340" stroke="${T.alert}" stroke-width="2"/><line x1="1106" y1="320" x2="1092" y2="340" stroke="${T.alert}" stroke-width="2"/>
    <text class="mono tiny" x="1099" y="356" text-anchor="middle" fill="${T.alert}">NEVER</text>

    <!-- Atlas under everything -->
    <rect x="64" y="${AY}" width="1472" height="64" rx="12" fill="${T.raised}" stroke="${T.mongo}" stroke-opacity=".85" stroke-width="1.4"/>
    <text class="mono title" x="82" y="${AY+28}" fill="${T.mongo}">MONGODB ATLAS · SANDBOX CLUSTER</text>
    <text class="sans body" x="82" y="${AY+48}" fill="${T.muted}">policies · checkpoints · plans · findings · measurements · media_index · transcripts · jobs · the demo firm. Vector index for transcripts. Provisioned by the atlas battery.</text>
    ${['apps → packages → @3pt/core','make check = build-all + typecheck + hub-check','scripts/worktree.sh · lane worktrees, verify worktrees'].map((t,i)=>`<rect x="${1000+i*0}" y="${AY-2}" width="0" height="0"/>`).join('')}
    <line x1="264" y1="${LANES[0].bottom+6}" x2="264" y2="${AY-4}" stroke="${T.mongo}" stroke-opacity=".5" stroke-dasharray="3 5" marker-end="url(#m-${T.mongo.slice(1)})"/>
    <line x1="792" y1="${LANES[1].bottom+6}" x2="792" y2="${AY-4}" stroke="${T.mongo}" stroke-opacity=".5" stroke-dasharray="3 5" marker-end="url(#m-${T.mongo.slice(1)})"/>
    <line x1="1328" y1="${LANES[2].bottom+6}" x2="1328" y2="${AY-4}" stroke="${T.mongo}" stroke-opacity=".5" stroke-dasharray="3 5" marker-end="url(#m-${T.mongo.slice(1)})"/>

    <text class="mono foot" x="64" y="${H-14}">RULES: apps → packages → @3pt/core · stages never import batteries · surfaces only over HTTP · RECIPES: docs/10-architecture.md §5 · DERIVED FROM THE TREE</text>
    <rect x=".5" y=".5" width="${W-1}" height="${H-1}" rx="12" fill="none" stroke="${T.line}"/>
  </g>
</svg>
`;
const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'docs', 'assets', 'architecture.svg');
writeFileSync(out, svg); console.log(`wrote ${out}`);
