#!/usr/bin/env node
// replay-data.mjs — run `3pt replay` and write its result as hub/site/replay-data.js (globalThis.REPLAY).
// The "How it works" leaf draws figure 7 from this file. Re-run after any change to the checks,
// the improver or data/mock/acme-builders:
//
//   pnpm turbo run build --filter @3pt/cli && node scripts/replay-data.mjs
//   node scripts/replay-data.mjs --cli <path/to/cli/dist/index.js>   # use a CLI built elsewhere
//
// It also verifies: the recounted grants, revokes, keeps and sprint modes must equal the replay's own
// summary line, and RUNS separate replays must print the same bytes, or it exits 1 and writes nothing.
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const i = process.argv.indexOf('--cli');
const cli = i > 0 ? process.argv[i + 1] : join(root, 'harness/apps/cli/dist/index.js');
// The CLI joins the data path to its own repo root, so it stays relative.
const RUNS = 3;   // the Results leaf shows this count; each run is a fresh process with a fresh memory store
const outs = Array.from({ length: RUNS }, () => execFileSync('node', [cli, 'replay', 'data/mock/acme-builders'], { cwd: root, encoding: 'utf8' }));
if (outs.some(o => o !== outs[0])) { console.error(`FAIL replay-data: ${RUNS} replays did not print the same output`); process.exit(1); }
const out = outs[0];
const lines = out.split('\n');

const head = out.match(/\[replay\] (\d+) projects, (\d+) months \((\d{4}-\d{2}) → (\d{4}-\d{2})\)/);
if (!head) throw new Error('replay-data: no header line in replay output');
const [, projects, nMonths, first] = head;

// Sprint mode per month, from the F/I/X strip. Months are consecutive from `first`.
const modeOf = { F: 'feature', I: 'improvement', X: 'fix' };
const strip = lines.filter(l => /^ {2}\d{4} {2}[FIX ]+$/.test(l)).flatMap(l => l.slice(8).split(' ').filter(Boolean));
const [y0, m0] = first.split('-').map(Number);
const label = k => { const t = y0 * 12 + (m0 - 1) + k; return `${Math.floor(t / 12)}-${String((t % 12) + 1).padStart(2, '0')}`; };
const months = strip.map((c, k) => ({ month: label(k), mode: modeOf[c], events: [] }));
if (months.length !== Number(nMonths)) throw new Error(`replay-data: strip has ${months.length} months, header says ${nMonths}`);

// Events per month: + granted, - revoked, = kept after debug, ✓ / ✗ effect check (printed on change only).
let cur = null;
for (const l of lines) {
  const m = l.match(/^\[replay\] (\d{4}-\d{2}) (\w+)\s+cp\/(\d+)\s+v(\d+) → v(\d+)/);
  if (m) { cur = months.find(x => x.month === m[1]); Object.assign(cur, { cp: +m[3], from: +m[4], to: +m[5] }); continue; }
  const e = l.match(/^ {11}([+\-=✓✗]) (.*)$/);
  if (!e || !cur) continue;
  const [, k, rest] = e;
  const grant = k === '+' ? rest.split(/\s+/)[0]
    : k === '-' ? rest.match(/^revoked (\S+):/)?.[1]
    : k === '=' ? rest.match(/^kept (\S+):/)?.[1]
    : rest.split(' ')[0];
  const note = k === '+' ? rest.slice(grant.length).trim() : rest;
  cur.events.push({ k, grant, note });
}

const tallyLine = out.match(/(\d+) feature · (\d+) improvement · (\d+) fix sprints; (\d+) grants, (\d+) confirmed, (\d+) failed effect checks, (\d+) revoked, (\d+) kept after debug/);
if (!tallyLine) throw new Error('replay-data: no summary line');
const said = { feature: +tallyLine[1], improvement: +tallyLine[2], fix: +tallyLine[3], granted: +tallyLine[4], confirmed: +tallyLine[5], failedEffect: +tallyLine[6], revoked: +tallyLine[7], kept: +tallyLine[8] };
const ev = k => months.reduce((s, m) => s + m.events.filter(e => e.k === k).length, 0);
const count = { feature: months.filter(m => m.mode === 'feature').length, improvement: months.filter(m => m.mode === 'improvement').length,
  fix: months.filter(m => m.mode === 'fix').length, granted: ev('+'), revoked: ev('-'), kept: ev('=') };
const drift = Object.keys(count).filter(k => count[k] !== said[k]);
if (drift.length) { console.error(`FAIL replay-data: recount differs from the replay summary on ${drift.join(', ')}`, count, said); process.exit(1); }

const finalLine = out.match(/policy v0 → v(\d+): build grants now (.*); (\d+) rules learned/);
const expected = lines.map(l => l.match(/^ {2}(\d+)\s+(\w+)\s+(\d{4}-\d{2})\s+(\d{4}-\d{2})\s+(\S+)\s+\((\S+)\)/)).filter(Boolean)
  .map(([, v, capability, expected, firstTry, now, grant]) => ({ v: +v, capability, expected, firstTry, now, grant }));

const data = {
  projects: +projects, first, last: months.at(-1).month, months, expected,
  final: { version: +finalLine[1], grants: finalLine[2].split(', '), rulesLearned: +finalLine[3] },
  runs: RUNS,   // replays run and found byte-identical
  said,   // the replay's own summary; `confirmed` and `failedEffect` count every effect check, not only changes
};
const file = join(root, 'hub/site/replay-data.js');
writeFileSync(file, `/* GENERATED by scripts/replay-data.mjs from \`3pt replay\` (harness/apps/cli/src/replay.ts). Do not edit. */\n` +
  `globalThis.REPLAY = ${JSON.stringify(data)};\n`);
console.log(`[replay-data] ${months.length} months, ${count.granted} grants, ${count.revoked} revoked, ${count.kept} kept → hub/site/replay-data.js`);
