// docmeta.mjs — per-document metadata the Viewer cannot derive at load: what git knows.
// Writes site/doc-meta.js (globalThis.DOCMETA, GENERATED) for every markdown document the hub ships
// (docs/**/*.md, README.md, brainstorming.md): last commit (sha, minute, subject), commit count,
// first commit minute, lines. Words and sections are DERIVED in the Viewer from the rendered text;
// git facts need history, and CI checks out shallow, so this file is committed and regenerated by
// `make -C hub meta` at every checkpoint (the same rule as replay-data.js).
//
//   node hub/tools/docmeta.mjs            writes site/doc-meta.js
//   node hub/tools/docmeta.mjs --check    exit 1 when site/doc-meta.js is older than the tree (a doc changed since)
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HUB = join(dirname(fileURLToPath(import.meta.url)), '..'), REPO = join(HUB, '..');
const OUT = join(HUB, 'site', 'doc-meta.js');
const git = (args) => execSync(`git ${args}`, { cwd: REPO, encoding: 'utf8' }).trim();
const files = git('ls-files -- "docs/**/*.md" "docs/*.md" README.md brainstorming.md').split('\n').filter(Boolean);
const meta = {};
for (const f of files) {
  const log = git(`log --format=%h%x09%ad%x09%an%x09%s --date=iso-strict -- "${f}"`).split('\n').filter(Boolean);
  if (!log.length) continue;
  const [sha, at, by, subject] = log[0].split('\t');
  const first = log[log.length - 1].split('\t')[1];
  const src = readFileSync(join(REPO, f), 'utf8');
  meta[f] = { sha, at, by, subject, commits: log.length, first, lines: src.split('\n').length };
}
if (git('rev-parse --is-shallow-repository') === 'true') { console.log('skip — shallow checkout, doc-meta.js left as committed'); process.exit(0); }
const head = git('rev-parse --short HEAD'), stamp = new Date().toISOString().slice(0, 16) + 'Z';
const body = `/* 3PT · doc-meta.js — GENERATED by hub/tools/docmeta.mjs at ${stamp} from ${head}; do not edit.
   What git knows about every markdown document the hub ships. The Viewer reads globalThis.DOCMETA[path]. */
(function(){ var G=(typeof globalThis!=='undefined'?globalThis:window); G.DOCMETA=${JSON.stringify(meta, null, 1)}; G.DOCMETA_AT=${JSON.stringify({ at: stamp, head })}; })();
`;
if (process.argv.includes('--check')) {
  if (!existsSync(OUT)) { console.error('FAIL: site/doc-meta.js missing — run make -C hub meta'); process.exit(1); }
  const cur = readFileSync(OUT, 'utf8');
  const stale = Object.entries(meta).filter(([f, m]) => !cur.includes(`"${f}"`) || !cur.includes(`"sha": "${m.sha}"`)).map(([f]) => f);
  if (stale.length) { console.error(`FAIL: site/doc-meta.js is stale for ${stale.length} document(s) (${stale.slice(0, 3).join(', ')}${stale.length > 3 ? ', …' : ''}) — run make -C hub meta`); process.exit(1); }
  console.log(`OK — doc-meta.js current for ${Object.keys(meta).length} documents`); process.exit(0);
}
writeFileSync(OUT, body);
console.log(`wrote site/doc-meta.js — ${Object.keys(meta).length} documents at ${head}`);
